---
- name: Set target_name var
  ansible.builtin.set_fact:
    target_name: "{{ hostvars['DUMMY']['host_name'] }}"
  
- name: Add entry to prometheus.yml
  ansible.builtin.lineinfile:
    path: /opt/prometheus/prometheus.yml
    insertafter: '      - targets: \[''localhost:9100''\]'
    regexp: '      - targets: \[''{{ target_name }}:{{ target_port }}''\]'
    line: "      - targets: ['{{ target_name }}:{{ target_port }}']"
  notify: Restart prometheus container