- name: Configure server for metrics
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: false
  become: true

  vars:
    msi_file: windows_exporter-0.19.0-amd64.msi
    collectors:
      - cpu
      - cs
      - logical_disk
      - os
      - system
      - net
      - service
    log_level: warn

  tasks:

    - name: Prestage program folder
      ansible.windows.win_file:
        path: C:\Program Files\windows_exporter
        state: directory

    # - name: Copy config file  
    #   ansible.windows.win_copy:
    #     src: config.yml
    #     dest: C:\Program Files\windows_exporter\config.yml

    - name: Use templating to create config file on remote host
      ansible.builtin.template:
        src: config.yml.j2
        dest: C:\Program Files\windows_exporter\config.yml
      notify:
        - Restart windows_exporter

    - name: Make sure c:\temp exists
      ansible.windows.win_file:
        path: C:\temp
        state: directory
    
    - name: Download windows exporter msi from github
      ansible.windows.win_get_url:
        url: https://github.com/prometheus-community/windows_exporter/releases/download/v0.19.0/{{ msi_file }}
        dest: C:\temp\{{ msi_file }}

    - name: Install windows_exporter
      ansible.windows.win_package:
        path: C:\temp\{{ msi_file }}
        product_id: '{344EDA7B-3B94-4E58-AD9C-BF019081C485}'
        arguments: 'EXTRA_FLAGS="--config.file=""C:\Program Files\windows_exporter\config.yml"""'
        state: present

    - name: Start windows_exporter service if not started and set to auto
      ansible.windows.win_service:
        name: windows_exporter
        start_mode: auto
        state: started

  handlers:

    - name: Restart windows_exporter
      ansible.windows.win_service:
        name: windows_exporter
        state: restarted

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become_user: poduser
  become_method: sudo

  tasks:

    - name: Add entry to prometheus.yml
      ansible.builtin.lineinfile:
        path: /opt/prometheus/prometheus.yml
        insertafter: '      - targets: \[''localhost:9100''\]'
        regexp: '      - targets: \[''{{ hostvar }}:9182''\]'
        line: "      - targets: ['{{ hostvar }}:9182']"
      ## Added notify ##
      notify:
        - Restart prometheus container
  
  ## Added handler##
  handlers:

    - name: Restart prometheus container
      containers.podman.podman_container:
        name: prometheus
        image: prom/prometheus:v2.36.2
        state: started
        restart: yes


