- name: Configure server for metrics
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: false
  become: true
  become_method: runas

  roles:  
    - install_windows_exporter

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become_user: poduser
  become_method: sudo

  roles:
    - update_prometheus





