- name: Configure server for metrics
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Create dummy host to store os_family
      ansible.builtin.add_host:
        name: "DUMMY"
        host_os: "{{ ansible_facts['os_family'] }}"
        host_name: "{{ inventory_hostname }}"
    
    - debug:
        var: hostvars['DUMMY']['host_os']
    - debug: var=hostvars['DUMMY']['host_name']