---
# tasks file for update_prometheus
- name: Add entry to prometheus.yml
  ansible.builtin.lineinfile:
    path: /opt/prometheus/prometheus.yml
    insertafter: '      - targets: \[''localhost:9100''\]'
    regexp: '      - targets: \[''{{ hostvar }}:{{ prom_port }}''\]'
    line: "      - targets: ['{{ hostvar }}:{{ prom_port }}']"
  notify:
    - Restart prometheus container